name: Update Token List

on:
  push:
    branches:
      - main

jobs:
  update-token-list:
    name: update-token-list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v4

      - name: Install deps
        run: npm install

      - name: Run the script
        env:
          CA_CERT: ${{ secrets.CA_CERT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PG_TOKENS_TABLE_NAME: ${{ secrets.PG_TOKENS_TABLE_NAME }}
          UPSTREAM_API_KEY: ${{ secrets.UPSTREAM_API_KEY }}
          UPSTREAM_TOKEN_LIST_API_URL: ${{ secrets.UPSTREAM_TOKEN_LIST_API_URL }}
        run: npm run update_token_list
